{{- if not .Values.job.oneShot -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: spring
spec:
  schedule: {{ required "if a job isn't one off it must have a schedule" .Values.job.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          initContainers:
          - name: rabbit-connect
            image: rabbit-connect:local
            env:
            - name: K_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RABBIT_HOST
              value: "rabbit-internal.$(K_NAMESPACE).svc.cluster.local"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USERNAME
              value: guest
            - name: RABBIT_PASSWORD
              value: guest
          containers:
          - name: job
            image: streamjobexample:local
            env:
            - name: K_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RABBIT_HOST
              value: "rabbit-internal.$(K_NAMESPACE).svc.cluster.local"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USERNAME
              value: guest
            - name: RABBIT_PASSWORD
              value: guest
{{- end }}
