apiVersion: v1
kind: Pod
metadata:
  name: rabbit
  labels:
    app: rabbit
spec:
  hostname: rabbit
  containers:
    - name: rabbit
      image: rabbit:local
      ports:
        - containerPort: 5672
          name: server
        - containerPort: 15672
          name: management
