apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbit
spec:
  selector:
    matchLabels:
      app: rabbit
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: rabbit:local
        ports:
        - containerPort: 5672
          name: server
        - containerPort: 15672
          name: management