apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  selector:
    app: rabbit
  type: ClusterIP
  ports:
  - protocol: TCP
    name: management
    port: 8080
    targetPort: 15672
  - protocol: TCP
    name: queue
    port: 5672
    targetPort: 5672