apiVersion: batch/v1
kind: Job
metadata:
  name: spring
  labels:
    app: spring-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: job
        image: streamjobexample:local
  backoffLimit: 1