apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: spring
spec:
  schedule: "0 0 31 2 ?" # 31 Feb means job will never run
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: job
            image: streamjobexample:local
